app = "new-api-proxy"
primary_region = "ord"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024


# postgres://newapi:niXl1YOXVBI4ur4@127.0.0.1:5433/newapi

